# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: npm install
  displayName: Install NPM packages

- script: sudo npm install -g @angular/cli
  displayName: Install @angular/cli

- script: sudo npm install -g ng-tailwindcss
  displayName: Install ng-tailwindcss via NPM

- script: npm run prestart
  displayName: Run ngtw build

- script: ng build --prod
  displayName: Build Angular

- task: CopyFiles@2
  displayName: Copy files to artifact directory
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishPipelineArtifact@1
  displayName: Publish artifact
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'

# - script: echo Hello, world!
#   displayName: 'Run a one-line script'

# - script: |
#     echo Add other tasks to build, test, and deploy your project.
#     echo See https://aka.ms/yaml
#   displayName: 'Run a multi-line script'